[project]
name = "vassoura"
version = "0.0.1a0"
description = "Unified feature-selection & reporting framework"
requires-python = ">=3.9"
authors = [{name = "Seu Nome", email = "you@example.com"}]
license = {text = "MIT"}
dependencies = [
    "pandas>=1.5",
    "numpy>=1.22",
    "scikit-learn>=1.3",
]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"
